#!/bin/bash

## Set Variables
DESTINATION=~/Library/Screen\ Savers

## Download the Screen Savers ZIP file
curl -Lo "/tmp/Screen Savers.zip" https://github.com/jaykepeters/Screen-Savers/raw/master/Screen%20Savers.zip --silent

## Unzip files to the temp directory
unzip -oqq "/tmp/Screen Savers.zip" -d /tmp

## Move Screen Savers to their respective folder
for f in /tmp/Screen\ Savers/*
do
	rsync -av "${f}" "$DESTINATION"
done

## Remove the ZIP 
rm -R "/tmp/Screen Savers.zip"

## Remove the Screen Saver folder
rm -R "/tmp/Screen Savers"

## Remove the macos foklder
rm -R "/tmp/__MACOSX"